[package]
name = "libaoc"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {  version = "0.11", features = [ "blocking" ] }
scraper = "0.18"
dirs = "5.0"