[package]
name = "libaoc"
version = "0.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {  version = "0.12", features = [ "blocking" ] }
scraper = "0.21"
dirs = "5.0"
html-escape = "0.2"